openapi: 3.0.0
info:
  title: platform
  version: '1.0'
  description: APIs for the FSI core platform services backend
  contact:
    name: Charles Odili
    email: chaluwa@gmail.com
  license:
    name: MIT
    url: 'https://github.com/fsi-sandbox/platform-backend/blob/main/LICENSE'
servers:
  - url: 'http://localhost:5000'
    description: Dev
paths:
  /v1/kpis/api-calls:
    get:
      summary: Get API Calls
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    message: Unable to proceed. Pls check your request data
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: Unable to proceed. Inssuficient user permissions
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: Error completing your request. Pls contact the admin or try again later
                    details: {}
      operationId: get-v1-kpis-sandbox-api-calls
      description: Get sandbox API calls count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
    parameters: []
  /v1/kpis/api-downloads:
    get:
      summary: Get API Downloads
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    message: Unable to proceed. Pls check your request data
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: Unable to proceed. Inssuficient user permissions
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: Error completing your request. Pls contact the admin or try again later
                    details: {}
      operationId: get-v1-kpis-sandbox-api-downloads
      description: Get sandbox API downloads count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
    parameters: []
  /v1/kpis/members/range:
    get:
      summary: Get Members
      tags:
        - KPIs
        - admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
      operationId: get-v1-kpis-sandbox-members
      description: Get sandbox members count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/members/devs/range:
    get:
      summary: Get Members Registered As Developers
      tags:
        - KPIs
        - admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
      operationId: get-v1-kpis-sandbox-devs
      description: Get sandbox developers count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/api-callers:
    get:
      summary: Get API Callers
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                request-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
      operationId: get-v1-kpis-api-callers
      description: Get sandbox API callers count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/api-downloaders:
    get:
      summary: Get API Downloaders
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                request-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthprized:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
      operationId: get-v1-kpis-api-downloaders
      description: Get sandbox API downloaders count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/sandbox-users:
    get:
      summary: Get Sandbox Users
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIFigureResponse'
              examples:
                success:
                  value:
                    outcome: 604
                    message: request completed in 305 milliseconds
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                request-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    message: 'Error completing your request. '
                    details: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server-error:
                  value:
                    message: 'Error completing your request. '
                    details: {}
      operationId: get-v1-kpis-sandbox-users
      description: Get sandbox users count for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
        - $ref: '#/components/parameters/usageMode'
  /v1/kpis/members/gender/range:
    get:
      summary: Get Member Gender Data
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIDataResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-kpis-members-gender-range
      description: Get sandbox members' gender data for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/members/location/range:
    get:
      summary: Get Member Location Data
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIDataResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-kpis-members-loc-range
      description: Get sandbox members' location data for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
  /v1/kpis/members/age/range:
    get:
      summary: Get Member Age Data
      tags:
        - admin
        - KPIs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIDataResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-kpis-members-age-range
      description: Get sandbox members' age data for a given period of time
      parameters:
        - $ref: '#/components/parameters/fromRange'
        - $ref: '#/components/parameters/toRange'
components:
  schemas:
    KPIFigureResponse:
      title: KPIFigureResponse
      type: object
      x-tags:
        - KPIs
        - admin
      description: HTTP response schema for Sandbox KPI figures
      properties:
        outcome:
          type: integer
          format: int32
          example: 604
          description: The number of API calls for the given date range
        message:
          type: string
          description: 'Optional response message for the KPI, e.g what the KPI actually was'
          example: request completed in 305 milliseconds
      required:
        - outcome
    ErrorResponse:
      title: ErrorResponse
      type: object
      x-tags:
        - admin
      description: Schema for error responses from the server
      properties:
        message:
          type: string
          example: 'Error completing your request. '
          description: A brief description of the error that occured or action the user might need to take
        details:
          type: object
          description: An optional dictionary of keys and values for the error raised
      required:
        - message
    KPIDataResponse:
      title: KPIDataResponse
      type: object
      properties:
        message:
          example: request completed in 305 milliseconds
          type: string
          description: 'Optional response message for the KPI, e.g what the KPI actually was'
        data:
          type: array
          items:
            type: object
      required:
        - data
      description: HTTP response schema for Sandbox KPI data
  parameters:
    toRange:
      name: toRange
      in: query
      required: true
      schema:
        type: string
        pattern: '^\d{13}$'
        minLength: 13
        maxLength: 13
        example: '1618255921030'
      description: UNIX timestamp of the end date (exclusive) for the data to include
    fromRange:
      name: fromRange
      in: query
      schema:
        type: string
        pattern: '^\d{13}$'
        minLength: 13
        maxLength: 13
        example: '1618255921030'
      description: UNIX timestamp of the start date (inclusive) for the data to include
      required: true
    usageMode:
      name: mode
      in: query
      required: true
      schema:
        type: string
        enum:
          - UN
          - INT
      description: How to combine the supported user dimensions (i.e API callers / downloaders)
tags:
  - name: admin
  - name: KPIs
